### ISSUE TITLE
Cannot Load Ads on Real Device

### ISSUE THREAD

**Issue by Karbiya** [StartApp-SDK/flutter-plugin#13]
Hi,

i already test the sdk on my simulator device, it's working well with ` startAppSdk.setTestAdsEnabled(true);` but when i try to run on real device with ` startAppSdk.setTestAdsEnabled(true);` and without it. the sdk showing an error

`I/flutter ( 9760): Error loading Rewarded Video ad: PlatformException(failed_to_receive_ad, null, null, null)
I/flutter ( 9760): Error loading Interstitial ad: PlatformException(failed_to_receive_ad, null, null, null)
E/flutter ( 9760): [ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: Null check operator used on a null value
E/flutter ( 9760): #0      AdsController.loadInterstitialAd.<anonymous closure> (package:cpns_gratis/infrastructure/dal/services/ads.dart:93)
E/flutter ( 9760): #1      FutureExtensions.onError.onError (dart:async/future.dart:1068)
E/flutter ( 9760): #2      _RootZone.runBinary (dart:async/zone.dart:1666)
E/flutter ( 9760): #3      _FutureListener.handleError (dart:async/future_impl.dart:177)
E/flutter ( 9760): #4      Future._propagateToListeners.handleError (dart:async/future_impl.dart:858)
E/flutter ( 9760): #5      Future._propagateToListeners (dart:async/future_impl.dart:879)
E/flutter ( 9760): #6      Future._completeError (dart:async/future_impl.dart:655)
E/flutter ( 9760): <asynchronous suspension>
E/flutter ( 9760): 
I/flutter ( 9760): Error loading Banner ad: PlatformException(failed_to_receive_ad, null, null, null)
I/flutter ( 9760): Error loading Banner ad: PlatformException(failed_to_receive_ad, null, null, null)
I/flutter ( 9760): Error loading Banner ad: PlatformException(failed_to_receive_ad, null, null, null)
I/flutter ( 9760): Error loading Banner ad: PlatformException(failed_to_receive_ad, null, null, null)
I/flutter ( 9760): Error loading Banner ad: PlatformException(failed_to_receive_ad, null, null, null)
I/flutter ( 9760): Error loading Banner ad: PlatformException(failed_to_receive_ad, null, null, null)
I/flutter ( 9760): Error loading Banner ad: PlatformException(failed_to_receive_ad, null, null, null)
I/flutter ( 9760): Error loading Banner ad: PlatformException(failed_to_receive_ad, null, null, null)`

i already put the application id on my androidmanifest and i already submit my app link on startapp.

thank you

**Comment by Karbiya** [comment]
Hi,

i already solved this issue.

I put the meta data inside activity, may bad. 

Thanks
